version: '3'
services:
  app:
    build: .
    restart: always
    devices:
      - /dev/gpiomem:/dev/gpiomem
    environment:
      - DEVICE_CONNECTION_STRING=<your device connection string>
