version: '3'
services:
  app:
    build: .
    privileged: true
    restart: always
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/mem:/dev/mem"
    environment:
      - CONNECTION_STRING=<insertconnectionstringhere>